# Kunstcollectie API Service Configuration

name = "kunstcollectie-api"

[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && npm run build"

[deploy]
startCommand = "cd backend && npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[env]
NODE_ENV = "production"
PORT = "3001"
DATABASE_URL = "${{ Postgres.DATABASE_URL }}"
JWT_SECRET = "kunstcollectie_secure_jwt_secret_2025"
FRONTEND_URL = "${{ kunstcollectie.RAILWAY_PUBLIC_DOMAIN }}"
