name = "kunstcollectie-api"

[build]
builder = "nixpacks"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[env]
NODE_ENV = "production"
PORT = "3001"
JWT_SECRET = "kunstcollectie_secure_jwt_secret_2025"
